version: '2'
services:
    zoo1:
        image: zookeeper
        restart: always
        volumes:
            - zoo1:/conf
            - zoo1:/data
            - zoo1:/datalog
        ports:
          - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        image: zookeeper
        restart: always
        ports:
          - 2182:2181
        volumes:
            - zoo2:/conf
            - zoo2:/data
            - zoo2:/datalog
        environment:
            ZOO_MY_ID: 2
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        image: zookeeper
        restart: always
        ports:
          - 2183:2181
        volumes:
            - zoo3:/conf
            - zoo3:/data
            - zoo3:/datalog
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    solr1:
        image: solr
        restart: always
        ports:
            - 8983:8983
        volumes:
            - solr1:/opt/solr/server/solr
            - solr1:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181,zoo2:2181,zoo3:2181
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    solr2:
        image: solr
        restart: always
        ports:
            - 8984:8983
        volumes:
            - solr2:/opt/solr/server/solr
            - solr2:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181,zoo2:2181,zoo3:2181
        depends_on:
          - zoo1
          - zoo2
          - zoo3

    solr3:
        image: solr
        restart: always
        ports:
            - 8985:8983
        volumes:
            - solr3:/opt/solr/server/solr
            - solr3:/opt/solr/server/logs
        environment:
            ZK_HOST: zoo1:2181,zoo2:2181,zoo3:2181
        depends_on:
          - zoo1
          - zoo2
          - zoo3

volumes:
    zoo1:    
    zoo2:
    zoo3:
    solr1:
    solr2:
    solr3: